heat_template_version: 2015-04-30

description: >
   HOT template (Heat Orchestration Template) for MC
##################################################
   # Parameters Part
##################################################

parameters:

  name:
    type: string
    label: Name
    description: Name of Instance

  image_id:
    type: string
    label: Image ID
    description: Image to be used for compute instance

  flavor:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used

  volume_id:
    type: string
    label: Volume ID
    description: Volume ID .

  
 ##############################
   # New Ports
 ##############################

  edn_port_id:
    type: string
    label: port details
    description: port for our instance
 
 #########################################
    # Network Interface
#########################################
 
  edn_tenant_v6_fixed_ip:
    type: string
    label: fixed ip details
    description: EDNv6 static IP


  edn_tenant_v6_IPV6_DEFAULTGW:
    type: string
    label: edn IP gateway
    description: NA

  edn_tenant_EDNv6_Netmask:
    type: string
    label: EDN IP netmask
    description: Network netmask


#####################################
## resources part
######################################

resources:
  my_vm1:
    type: OS::Nova::Server
    properties:
      name: { get_param: name }
      image: { get_param: image_id }
      flavor: { get_param: flavor }
      config_drive: true
      networks:
        - port: { get_param: edn_port_id }
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/sh
            # IP address configurations
            nmcli con delete "System eth0"
            nmcli con add type ethernet con-name "eth0" ifname eth0 connection.autoconnect yes ipv6.method manual ipv6.addresses "$edn_tenant_v6_fixed_ip/$edn_tenant_EDNv6_Netmask" gw6 "$edn_tenant_v6_IPV6_DEFAULTGW" 802-3-ethernet.mtu 1500

            printf "[main]\ndns=none" > /etc/NetworkManager/conf.d/90-dns-none.conf
            systemctl restart NetworkManager

          params:
            # Common Network Interface
            $edn_tenant_v6_fixed_ip: { get_param: edn_tenant_v6_fixed_ip }
            $edn_tenant_v6_IPV6_DEFAULTGW: { get_param: edn_tenant_v6_IPV6_DEFAULTGW }
            $edn_tenant_EDNv6_Netmask: { get_param: edn_tenant_EDNv6_Netmask }


#-------------------------------------------------------------------------------

####################################
# volume attachment part
####################################
  volume_attachment:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id: { get_param: volume_id }
      instance_uuid: { get_resource: my_vm1 }














