heat_template_version: 2016-10-14

description: >
   HOT template (Heat Orchestration Template) for EINIF

#####################################
## Parameters part
######################################

parameters:
  # VM Resource
  name:
    type: string
    label: Name
    description: Name of Instance

  image_id:
    type: string
    label: Image ID
    description: Image to be used for compute instance

  flavor:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used

  volume_id:
    type: string
    label: Volume ID
    description: Volume ID .


##############################
  # New Ports
#############################

  ssn1_port_id:
    type: string
    label: ssn1 port
    description: port details for our instance

  ssn2_port_id:
    type: string
    label: ssn2 port
    description: port details for our instance

  ran_port_id:
    type: string
    default: ""
    label: ran port
    description: port details for our instance

  edn_port_id:
    type: string
    label: edn port
    description: port details for our instance
    
#  private_port_id:
#   type: string
#   label: port details
#   description: port for our instance

 
 #########################################
  # Network Interface
 #########################################

  edn_tenant_v4_GATEWAY:
    type: string
    label: EDN IP gateway
    description: Network gateway  
    
  edn_tenant_v4_Netmask:
    type: string
    label: EDN IP netmask
    description: Network netmask 

  edn_tenant_v6_IPV6_DEFAULTGW:
    type: string
    label: EDN IPv6 Gateway
    description: Network gateway 

  edn_tenant_EDNv6_Netmask:
    type: string
    label: EDN IPv6 netmask
    description: NA

  edn_tenant_v4_fixed_ip:
    type: string
    label: edn IPv4 fixed ip
    description: private static IP

  edn_tenant_v6_fixed_ip:
    type: string
    label: edn IPv6 IP 
    description: private static IP

#  private_ip:
#    type: string
#    label: privete IP
#    description: private IP

#  private_Netmask:
#    type: string
#    label: private netmask
#    description: NA

#  private_GATEWAY:
#    type: string
#    label: Private Gateway
#    description: Private Gateway



  ssn1_tenant_v4_GATEWAY:
    type: string
    label: ssn1 ipv4 Gateway
    description: Network gateway . 
    
  ssn1_tenant_v4_Netmask:
    type: string
    label: ssn1 IPv4 Netmask
    description: Network netmask .

  ssn1_tenant_v4_fixed_ip:
    type: string
    label: ssn1 IPV4 FIXED IP
    description: private static IP
    
  ssn2_tenant_v4_GATEWAY:
    type: string
    label: SSN2 IPv4 Gateway
    description: Network gateway . 
    
  ssn2_tenant_v4_Netmask:
    type: string
    label: SSN2 IPv4 Netmask
    description: Network netmask .

  ssn2_tenant_v4_fixed_ip:
    type: string
    label: ssn2 private fixed IP
    description: private static IP
  
  ran_tenant_v6_IPV6_DEFAULTGW:
    type: string
    label: ran IPv6 Gateway
    default: ""
    description: Network gateway 
    
  ran_tenant_v6_fixed_ip:
    type: string
    label: ran IPv6 private fixed IP
    default: ""
    description: private static IP
     

  ran_tenant_EDNv6_Netmask:
    type: string
    label: ran IPv6 netmask
    description: NA

resources:
#<<<<<<<--------------------->>>>>>>>>
  my_vm1:
    type: OS::Nova::Server
    properties:
      name: { get_param: name }
      image: { get_param: image_id }
      flavor: { get_param: flavor }
      networks:
        - port: { get_param: edn_port_id }
        - port: { get_param: ssn1_port_id }
        - port: { get_param: ssn2_port_id }
        - port: { get_param: ran_port_id }
      config_drive: true
      user_data:
        str_replace:
          template: |
            #!/bin/sh
            # IP address configurations
            nmcli con delete "System eth0"
            nmcli con add type ethernet con-name "eth0" ifname eth0 connection.autoconnect yes ipv6.method manual ipv6.addresses "$edn_tenant_v6_fixed_ip/$edn_tenant_EDNv6_Netmask" gw6 "$edn_tenant_v6_IPV6_DEFAULTGW" 802-3-ethernet.mtu 1500
            nmcli con modify eth0 ipv4.addresses "$edn_tenant_v4_fixed_ip/$edn_tenant_v4_Netmask" gw4 "$edn_tenant_v4_GATEWAY" ipv4.method manual
            printf "[main]\ndns=none" > /etc/NetworkManager/conf.d/90-dns-none.conf
            systemctl restart NetworkManager

            sed -i 's/PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config && systemctl restart sshd
            sed -i '1 s/$/ snmphost/' /etc/hosts
#            printf "\nClientAliveInterval 120\nClientAliveCountMax 720\n" >> /etc/ssh/sshd_config

          params:
                $edn_tenant_v4_GATEWAY: { get_param: edn_tenant_v4_GATEWAY}
                $edn_tenant_v4_Netmask: { get_param: edn_tenant_v4_Netmask}
                $edn_tenant_v6_IPV6_DEFAULTGW: {get_param: edn_tenant_v6_IPV6_DEFAULTGW}
                $edn_tenant_EDNv6_Netmask}: {get_param: edn_tenant_EDNv6_Netmask}
                $edn_tenant_v6_fixed_ip: {get_param: edn_tenant_v6_fixed_ip}
                $edn_tenant_v4_fixed_ip: {get_param: edn_tenant_v4_fixed_ip}



####################################
# volume attachment part
####################################
  volume_attachment:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id: { get_param: volume_id }
      instance_uuid: { get_resource: my_vm1 }
