heat_template_version: 2015-04-30

description: >
   HOT template (Heat Orchestration Template) for EIMGMT

#####################################
## Parameters part
######################################

parameters:

  name:
    type: string
    label: Name
    description: Name of Instance

  image_id:
    type: string
    label: Image ID
    description: Image to be used for compute instance

  flavor:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used

  volume_id:
    type: string
    label: Volume ID
    description: Volume ID .


##############################
    # Network  Ports
##############################

  edn_port_id:
    type: string
    label: port details
    description: port details for our instance

#########################################
   # Network Interface
##########################################

  edn_tenant_v6_IPV6_DEFAULTGW:
    type: string
    label: endv6 IP gateway
    description: Network gateway 
    
  edn_tenant_v6_fixed_ip:
    type: string
    label: ednv6 ip
    description: private static IP

#####################################
## resources part
#####################################

resources:
  my_vm1:
    type: OS::Nova::Server
    properties:
      name: { get_param: name }
      image: { get_param: image_id }
      flavor: { get_param: flavor }
      config_drive: true
      networks:
        - port: { get_param: edn_port_id }

      user_data_format: RAW
      user_data:
        str_replace:
          template: |
               #!/bin/sh
               printf "DEVICE=eth0\nBOOTPROTO=static\nONBOOT=yes\nTYPE=Ethernet\nUSERCTL=no\nIPV6INIT=yes\nIPV6ADDR=$edn_tenant_v6_fixed_ip\nIPV6_DEFAULTGW=$edn_tenant_v6_IPV6_DEFAULTGW\n" > /etc/sysconfig/network-scripts/ifcfg-eth0
               sed -i 's/^PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
               systemctl restart sshd
               systemctl restart network

          params:
                $edn_tenant_v6_IPV6_DEFAULTGW: { get_param: edn_tenant_v6_IPV6_DEFAULTGW } 
                $edn_tenant_v6_fixed_ip: { get_param: edn_tenant_v6_fixed_ip }


####################################
# volume attachment part
####################################
  volume_attachment:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id: { get_param: volume_id }
      instance_uuid: { get_resource: my_vm1 }



